name: Test code and app
on: 
  pull_request:
    branches: [main]
      
jobs:
  test_model:
    name: Test processed code and model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Pull data
        env:
          dags_user: ${{ secrets.DAGSHUB_USER }}
          dags_password: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user dags_user
          dvc remote modify origin --local password dags_password
          dvc pull --remote origin
